### PR TITLE
Next execution date

### PR DESCRIPTION
**Pull request by perryao**

### CODE REVIEW

**Comment by joshuathompson** [comment]
If we set nextExecutionDate to `null` then we can end up with situations like this:

`testArray = [{ date: new Date('8/9/2017') }];`
`executionDate = new Date('8/8/2017');`
`nextExecutionDate = null;` OR `nextExecutionDate = new Date(null);`
`console.log(testArray.filter(function(item) { return item.date > executionDate })`

This will filter correctly and print an array with the object we defined.  If we change it to this:

`console.log(testArray.filter(function(item) { return item.date > executionDate && item.date < nextExecutionDate })`

then we will filter out the item.

Are we okay with saying that the user has to verify whether or not nextExecutionDate is null?  Do we define nextExecutionDate as some infinitely high value if it's `null`?

**Comment by perryao** [comment]
@joshuathompson the challenge is that nextExecutionDate being null is a valid expectation set by airflow itself. It really only affects @once dags. I'm not sure what a reasonable default date would be, but yea we could possibly just set it to a really far date in the future.

**Comment by joshuathompson** [comment]
It's probably not worth it with only @once being effected.  Looks good to me otherwise.

**Comment by trong-le** [comment]
if it only affects @once, then I don't think the value of nextExecutionDate would matter since we're not worrying about future runs. I think null would be valid vs some arbitrary value that we might have to worry about in the future

**Pull request merged**
